### PR TITLE
Fix _changed? BC break and introduce algolia_dirty? method

### LINKED ISSUE #140: Please document criteria for smart _changed? behavior better
it goes unsaid, but if your setup uses tags or an `:if` or `:unless` option, algoliasearch-rails will attempt to do things like examine

`_tags_changed?` and whatever your `:if` condition symbol name is + `_changed?` as well. this is pretty hard to track down if you're wondering why your app is doing a lot of frivolous updates.

please also consider adding a method that can override `algolia_must_reindex?` entirely.

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | yes    
| BC breaks?        | no     
| Related Issue     | Fix #140   
| Need Doc update   | yes

## Describe your change

We recently made some change to handle the new `will_save_change_to_#{attr}?` instead of the deprecated `#{attr}_changed?`. See #325

I didn't realize that this was breaking backward compat' because we check your ActiveRecord version. So if you upgrade, existing methods named `#{attr}_changed?` won't be called.

I refactored it to the "first responding method", both will be tested, regardless of your Rails version. I added more tests for this.

### `algolia_dirty?` method

I added this in the same PR but it could be removed to merge the fix independantly. I added a method called `algolia_dirty?`, you can define it to override the calls to all  _changed? method. I think this could be useful in case you need to define many _changed? method or to handle multiple relationships.

Please any feedback on this one is appreciated 🙏 

```ruby
class Ebook < ActiveRecord::Base
  include AlgoliaSearch

  algoliasearch :synchronous => true, :index_name => safe_index_name("eBooks")do
    attributesToIndex [:name]
  end

  def algolia_dirty?
    self.author.custom_modified_recently?
  end
end
```

📝 **DOC**: Doc update is one the way.

### CODE REVIEW

File: lib/algoliasearch-rails.rb [hunk 1]
```diff
@@ -920,13 +923,16 @@ def algolia_find_in_batches(batch_size, &block)
...
-        "will_save_change_to_#{attr}?"
-      else
-        "#{attr}_changed?"
+    def algolia_attribute_changed?(object, attr_name)
+      # if one of two method is implemented, we return its result
+      # true/false means whether it has changed or not
+      ["#{attr_name}_changed?", "will_save_change_to_#{attr_name}?"].each do |method_name|
+        if object.respond_to?(method_name)
+          return object.send(method_name)
+        end
```
Comment (jeromedalbert) [inline lib/algoliasearch-rails.rb]: Wouldn't this code essentially always call `#{attr_name}_changed?`, since on any random Rails model, calling `model.respond_to?(:xxx_changed?)` returns true for all model attributes?

If so, this would essentially nullify #325, which means that on Rails 5.1 this gem would revert to its old behavior i.e. it would start emitting warnings again.

As a reminder, the deprecation warning in Rails 5.1 was:

> DEPRECATION WARNING: The behavior of `attribute_changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute?` instead.

I believe this warning was removed in Rails 5.2 as they changed the behavior (I guess). But `xxx_changed?` still exists and will likely always exist.

**Comment by jeromedalbert** [comment]
What is the problem this PR is trying to fix? Is it to make `#{attr}_changed?` methods work again? But why make them work again, since their behavior is getting deprecated/changed in Rails?

Is it because people redefine `xxx_changed?` for custom/complex attributes as defined by https://github.com/algolia/algoliasearch-rails#custom-attribute-definition:

```
## Custom attribute definition

You can use a block to specify a complex attribute value

```ruby
class Contact < ActiveRecord::Base
  include AlgoliaSearch

  algoliasearch do
    attribute :email
    attribute :full_name do
      "#{first_name} #{last_name}"
    end
    add_attribute :full_name2
  end

  def full_name2
    "#{first_name} #{last_name}"
  end
end

***Notes:*** As soon as you use such code to define extra attributes, the gem is not anymore able to detect if the attribute has changed (the code uses Rails's `#{attribute}_changed?` method to detect that). As a consequence, your record will be pushed to the API even if its attributes didn't change. You can work-around this behavior creating a `_changed?` method:

```ruby
class Contact < ActiveRecord::Base
  include AlgoliaSearch

  algoliasearch do
    attribute :email
    attribute :full_name do
      "#{first_name} #{last_name}"
    end
  end

  def full_name_changed?
    first_name_changed? || last_name_changed?
  end
end
```

^ If the goal of this PR is to support this use case and only this use case (i.e. assuming people only define `_changed` for custom/complex attributes), then I see 2 possible solutions:

1. Make the code in this PR call `:xxx_changed?` only if `xxx` is a custom/complex attribute. A custom/complex attribute is basically an attribute that is not a Rails attribute i.e.`!u.has_attribute?(:xxx)`.

2. Change the doc instructions+code not to use `xxx_changed?` for complex attributes, i.e. replace `_changed` by a new term in order not to clash with Rails.

**Comment by simonireilly** [comment]
I think you are handling this correctly :+1: 

There will be many apps that use <= rails 5.1 for years to come so it should be supported.

There are maybe 20 ways to do this but...

I think the loop to call both the methods is simple and good! If we try to be clever we just create edge cases!!

 :+1: for your implementation.

File: lib/algoliasearch-rails.rb (hunk 1 above)
Comment (julienbourdeau) [reply lib/algoliasearch-rails.rb]: Yes, I agree. I don't know why I didn't see it myself. I guess after trying a few things, I started ignoring some cases. I was really looking to restore the previous behavior. 😅 
I definitely don't want to see those warning in more recent rails version 👍

**Comment by julienbourdeau** [comment]
Thank you @jeromedalbert and @simonireilly for your precious feedback, I really appreciate it 🙏 

I looked for a better solution inspired by all @jeromedalbert's ideas. I think I found a fairly safe way to check whether `#{attr_name}_changed?` is user-defined or autmatic Rails method.

```ruby
rails_magic_def = object.method(method_name).source_location[0].end_with?("active_model/attribute_methods.rb")
```

I think now, all the different scenario are handled, backward-compatibility is restored and deprecated method shouldn't be used. I'm going to add more tests to ensure that 👍 

Again, any feedback is more than welcome. Thank you very much for helping me on this!

**Comment by jeromedalbert** [comment]
Wow that is some high-level code introspection right there. 😂 

Looks good to me.

File: Gemfile [hunk 2]
```diff
@@ -3,6 +3,10 @@ source "http://rubygems.org"
 gem 'json', '~> 1.8', '>= 1.8.6'
 gem 'algoliasearch', '>= 1.17.0', '< 2.0.0'
 
+if defined?(RUBY_VERSION) && RUBY_VERSION == "1.8.7"
+  gem 'ruby18_source_location'
+end
+
```
Comment (redox) [inline Gemfile]: Why do we need that @julienbourdeau ? Doesn't seem to be a very popular library.

File: lib/algoliasearch-rails.rb [hunk 3]
```diff
@@ -920,13 +923,47 @@ def algolia_find_in_batches(batch_size, &block)
...
+      end
+
+      # Nil means we don't know if the attribute has changed
+      nil
+    end
+
+    def automatic_changed_method?(object, method_name)
+      raise ArgumentError.new("Method #{method_name} doesn't exist on #{object.class.name}") unless object.respond_to?(method_name)
+      if defined?(:RUBY_VERSION) && RUBY_VERSION.to_f < 1.9
+        file = object.method(method_name).__file__
```
Comment (redox) [inline lib/algoliasearch-rails.rb]: So this test is wrong if you want to handle `source_location` in `1.8`.

Comment (julienbourdeau) [reply lib/algoliasearch-rails.rb]: Arf I forgot to remove it.

File: Gemfile (hunk 2 above)
Comment (julienbourdeau) [reply Gemfile]: `source_location` is only available after in ruby 1.9, this gem backports the feature to 1.8.
I thought `__file__` should work with ruby < 1.9 but I got undefined method in Travis as well.

One other solution would be to not have this feature in Ruby < 1.9 and in this case we always call `attr_changed?` method. In this case, people won't be able to use the new name but you can't run Rails 5 on ruby 1.8, I don't think it's important.

Now, that I think about it, It might be the best solution. WDYT?

Comment (redox) [reply Gemfile]: I think always calling the `attr_changed?` method is fine, it's what we've done before; no?

> In this case, people won't be able to use the new name but you can't run Rails 5 on ruby 1.8, I don't think it's important.

Correct

> Now, that I think about it, It might be the best solution. WDYT?

Most probably. Also, what you've done is not enough: the `Gemfile` is handling the dependencies of the project, while the dependencies that are gonna be bundled while releasing the gem is defined in `algoliasearch-rails.gemspec`. There should be a single mutualized list for both, but the fact we're having extra dependencies based on the ruby VM/versions makes it impossible.

Comment (julienbourdeau) [reply Gemfile]: Thank you Sylvain for reminding me about `algoliasearch-rails.gemspec`. When writing this "fix" it totally went over my head 😅 🙏
