### PR TITLE
fix: only check current settings when indexing enabled

### LINKED ISSUE #412: index_name/settings  end point still being called while disable_indexing: true
- Rails version: 6.1.4.1
- Algolia Rails integration version: 2.1.3
- Algolia client version: 2.1.1
- Language Version: 2.6.7

### Description

It is my expectation that with `disable_indexing: Rails.env.test?`, there will be no http calls needed anymore for tests to pass without any internet connection. 

However it seems to be still calling the `:index_name/settings` end point and my tests are failing because of it.

The workaround would be to use `vcr` to cache/mock the responses, but what if I didn't want new dependencies like that?

### Steps To Reproduce

- Index an ActiveRecord model, DummyRecord with `disable_indexing: Rails.env.test?` 
- `DummyRecord.create` in test environment with internet disabled in a test type that is not model/view/controller. In my case, I am creating a record in a component test for ViewComponent.

### PR DESCRIPTION
**Pull request by DevinCodes**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no    
| BC breaks?        | no     
| Related Issue     | Fix #412 
| Need Doc update   | no

## Describe your change
This prevents a call to `get_settings` when indexing is disabled.

### CODE REVIEW

**Comment by waynehoover** [comment]
any updates on getting this merged? As it is now this is causing our test suite to fail.

File: spec/integration_spec.rb [hunk 1]
```diff
@@ -349,6 +359,13 @@ def public?
   end
 end
 
+describe 'DisabledIndexing' do
```
Comment (Whitespace) [inline spec/integration_spec.rb:362]: A spec to add:
- other classes should call get_settings

A spec to maybe add?:
- DisabledIndexing should check_settings

Nit: the case of `DisabledIndexing` is strange.  I would have thought `DisabledIndex` maybe?  There are other classes that are pluralized in this file and some that are singular.  It's unclear to me if `Indexing` is the correct choice or something else is preferable.

Comment (DevinCodes) [reply spec/integration_spec.rb:362]: > A spec to add:
> * other classes should call get_settings

This is tested implicitly, but I've added an explicit test in d77de87ee2080d2c8122453e289530f5410cb7a6.

Regarding the naming, I went with `Indexing` to refer to the action of indexing, and preventing confusion with `Index` objects. It follows the same convention as other `disabled_*` 'models' we have in these tests 🙂
