### PR TITLE
Fix #352 and #353 

### LINKED ISSUE #352: 1.22 breaking change
- Rails version: 5.1.6
- Algolia Rails integration version:  1.22

### Description
https://github.com/algolia/algoliasearch-rails/pull/338 introduced a few
breaking changes (including 1 fixed in https://github.com/algolia/algoliasearch-rails/pull/350).

https://github.com/algolia/algoliasearch-rails/pull/338/files#diff-dfaec67e907148ea8211e17340f0f30cR749 changed the behavior
for when `<attribute>_changed?` doesn't exist. Previously it would
be conservative and always auto-index if there are custom attributes. 
Now it will assume no changes are necessary 

### Steps To Reproduce
```rb
class AnyModel < ActiveRecord::Base
  include AlgoliaSearch
  algoliasearch do
    attribute(:not_a_column) { some_column + 1 }
  end
end

instance_of_model.update!(some_column: 3) # will not trigger algolia update
```

### PR DESCRIPTION
**Pull request by Gasparila**
| Q                 | A
| ----------------- | ----------
| Bug fix?          | yes
| New feature?      | no
| BC breaks?        | no     
| Related Issue     | Fix #352 #353
| Need Doc update   | no

Fix breaking change introduced in #352
According to the [documentation](https://github.com/algolia/algoliasearch-rails/blob/master/README.md#custom-attribute-definition),
using custom attributes without a custom `_changed?` method will always
cause changes to push to the API. This behavior was lost in #338

Fix unexpected behavior during transactions #353
`@algolia_must_reindex` is reset in every validate call. This means that a record
that is updated multiple times in a transaction will only be indexed if the
final update marks as must reindex. Update the code so that once
`@algolia_must_reindex` is marked as `true`, it remains true until
explicitly unset in `algolia_perform_index_tasks`

### CODE REVIEW

File: lib/algoliasearch-rails.rb [hunk 1]
```diff
@@ -953,8 +953,8 @@ def algolia_attribute_changed?(object, attr_name)
         return object.send("will_save_change_to_#{attr_name}?")
       end
 
-      # Nil means we don't know if the attribute has changed
-      nil
+      # We don't know if the attribute has changed, so conservatively assume it has
+      true
```
Comment (julienbourdeau) [inline lib/algoliasearch-rails.rb]: 👍

**Comment by julienbourdeau** [comment]
Hi @Gasparila ,

Thank you very much for this PR, this is very valuable 🙏
